module.exports = {
  top5: [
    {
      prize: '1M Comedian',
      name: '@connor',
      country: 'From UK'
    },{
      prize: '1M Style Guru',
      name: '@klatex',
      country: 'From Poland'
    },{
      prize: ' 1M Talent',
      name: '@giuliapennaofficial',
      country: 'From Italy'
    },{
      prize: '1M Sports Guru',
      name: '@jeremhry',
      country: 'From France'
    },{
      prize: '1M Foodie',
      name: '@kuchennykodeks',
      country: 'From Poland'
    }
  ],
  top100: {
      'Top 6-20': [
       "@team.ragnarok",
       "@christiina_nielsen",
       "@benflat",
       "@rezbkr",
       "@uglyleo",
       "@jaaerh",
       "@__l.a.u.r.e__",
       "@dcfreestyle_official",
       "@bloodydjan",
       "@harrietfreestyle",
       "@outthebox",
       "@simmylanda",
       "@laurieelle",
       "@rachelward_e",
       "@kamelemona",
      ],
      'Top 21-50':[
       "@nylaa.a",
       "@theammisuyoutube",
       "@telj",
       "@daddydepp23",
       "@polly_dance_",
       "@raymvsic",
       "@martingeco",
       "@denis_sfitlic",
       "@terysa18",
       "@mikebraxton",
       "@hannahnasshaha",
       "@chivalroustube",
       "@clind1",
       "@alexisfurler",
       "@benblack10",
       "@aula39",
       "@lucas_paris",
       "@robinbirrell",
       "@khalilkhalidy",
       "@magicsingh",
       "@damianbuczek",
       "@aidouush",
       "@paulinapaola",
       "@chichou34",
       "@safir_jaune",
       "@aaksa_",
       "@sachasmiles",
       "@kubapost",
       "@wyobraznia",
       "@imnickrobertson",
      ],
      'Top 51-100' : [
       "@vickybanham",
       "@sanofficial",
       "@ginyventu",
       "@kjormo",
       "@quellocheledonne",
       "@skillscrewhd",
       "@jasongagliani",
       "@danoshi",
       "@vittorio_loffredo",
       "@danigregersen",
       "@missmammasorriso",
       "@carrieblak",
       "@majkolmannen",
       "@robertocasuccio",
       "@sakkoz_beatbox",
       "@leonardo_marchetti",
       "@mariannacursio",
       "@lucagallone",
       "@hannah",
       "@zackandlife",
       "@jamiefreestyle",
       "@laurbubble",
       "@beckilouise_c",
       "@markharlow_official",
       "@ionescuandrei",
       "@lenakomi",
       "@kutasjuli",
       "@imdreu",
       "@sebastiankowalczykkk",
       "@adamżakiewicz",
       "@filipzabielski",
       "@zietkowsky",
       "@izabelazabielska",
       "@ciapur",
       "@juliazugaj",
       "@nataliasisik",
       "@kamilpodobas",
       "@chardain_95",
       "@bedialy",
       "@poppinnston",
       "@floriancarli",
       "@ibenchabrown",
       "@mike_bolivar",
       "@kingcapuche",
       "@loligraciossa",
       "@nbcover",
       "@noem.musik",
       "@tristan.duc",
       "@melodiedkn",
       "@homme.vert",
      ]
    }
}